service: save-records-dynamo-tesis

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  # iamRoleStatements: # Se crea un rol con los permisos necesarios para interactuar con DynamoDB
  #   - Effect: "Allow"
  #     Action:
  #       - dynamodb:Query
  #       - dynamodb:DescribeTable
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:UpdateItem
  #       - dynamodb:DeleteItem
  #       - dynamodb:BatchWriteItem
  #       - dynamodb:PutItem
  #     Resource: # Le indicamos el recurso para el cual aplica el rol en cuestión
  #       - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.POLLS_TABLE_NAME}
  #       - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.POLLS_TABLE_NAME}/index/ListPollsTitles
  environment: ${file(config/serverless/environment/env.yml)}

package:
  individually: true
  patterns:
    - '!./**'
    - ./node_modules/**

plugins:
  - serverless-pseudo-parameters
  - serverless-step-functions

stepFunctions:
  stateMachines:
    pipeline: ${file(config/serverless/step-function/pipeline.yml)}
  DependsOn: ResultsQueue


functions:
  - ${file(config/serverless/functions/results/results_functions.yml)}

resources:
  - ${file(config/serverless/sqs/sqs.yml)}
