service: save-records-dynamo-tesis

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  iamRoleStatements: # Se crea un rol con los permisos necesarios para interactuar con DynamoDB
    - Effect: "Allow"
      Action:
        - states:StartExecution
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.POLLS_TABLE_NAME}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.POLLS_TABLE_NAME}/index/ListPollsTitles
        - ${self:provider.environment.STEP_FUNCTION_ARN}
  environment: ${file(config/serverless/environment/env.yml)}

package:
  individually: true
  patterns:
    - '!./**'
    # - ./node_modules/**

plugins:
  - serverless-pseudo-parameters
  - serverless-step-functions

stepFunctions:
  stateMachines:
    pipeline: ${file(config/serverless/step-function/pipeline.yml)}


functions:
  - ${file(config/serverless/functions/results/results_functions.yml)}
  - ${file(config/serverless/functions/start-process/start_process.yml)}
  - ${file(config/serverless/functions/polls/polls_functions.yml)}
  - ${file(config/serverless/functions/incrementer/incrementer_function.yml)}

resources:
  - ${file(config/serverless/sqs/sqs.yml)}
