saveRandomResultsBot:
  handler: src/bot/botHandler.run
  package:
    patterns:
      - src/bot/**
  events:
    - http:
        path: /bot/run
        method: get
callBot:
  handler: src/bot/botHandler.callBot
  timeout: 15
  package:
    patterns:
      - src/bot/**
  events:
    - http:
        path: /bot/callBot
        method: get