addResult:
  handler: src/api/handlers/results/resultHandler.addResult
  package:
    patterns:
      - src/api/handlers/results/**
  events:
    - http: # Se indica que el evento se disparará mediante una solicitud http
        path: /result
        method: post