addResult:
  handler: src/api/handlers/results/resultHandler.addResult
  package:
    patterns:
      - src/api/handlers/results/**
  events:
    - http: # Se indica que el evento se disparará mediante una solicitud http
        path: /results
        method: post
# addRandomResult:
#   handler: src/api/handlers/results/resultHandler.addRandomResult
#   package:
#     patterns:
#       - src/api/handlers/results/**
#   events:
#     - http:
#         path: /result/randomResult
#         method: post