createResult:
  handler: src/api/handlers/results/createResult/createResultHandler.createResult
  package:
    patterns:
      - src/api/handlers/results/createResult/**
  events:
    - http:
        path: /results
        method: post
getResult:
  handler: src/api/handlers/results/getResult/getResultHandler.getResult
  package:
    patterns:
      - src/api/handlers/results/getResult/**
  events:
    - http:
        path: /results/{id}
        method: get
createRandomResult:
  handler: src/api/handlers/results/createRandomResult/createRandomResultHandler.createRandomResult
  package:
    patterns:
      - src/api/handlers/results/createRandomResult/**
  events:
    - http:
        path: /results/randomResults
        method: post
updateResult:
  handler: src/api/handlers/results/updateResult/updateResultHandler.updateResult
  package:
    patterns:
      - src/api/handlers/results/updateResult/**
  events:
    - http:
        path: /results/{id}
        method: put
deleteResult:
  handler: src/api/handlers/results/deleteResult/deleteResultHandler.deleteResult
  package:
    patterns:
      - src/api/handlers/results/deleteResult/**
  events:
    - http:
        path: /results/{id}
        method: delete

