Resources:
  FormsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:provider.environment.FORMS_TABLE_NAME}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "GSI1PK"
          AttributeType: "S"
        - AttributeName: "title"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: ListFormsTitles
          KeySchema:
            - AttributeName: "GSI1PK"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - title
            ProjectionType: "INCLUDE"
        - IndexName: SearchFormByTitle
          KeySchema:
            - AttributeName: "title"
              KeyType: "HASH"
            - AttributeName: "PK"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

