createForm:
  handler: com.serverless.forms.createform.CreateFormHandler
  memorySize: 512
  timeout: 15
  events:
    - http:
        path: /forms
        method: post
getFormByTitle:
  handler: com.serverless.forms.getformbytitle.GetFormByTitleHandler
  memorySize: 512
  timeout: 15
  events:
    - http:
        path: /forms/getFormByTitle
        method: get
updateForm:
  handler: com.serverless.forms.updateform.UpdateFormHandler
  memorySize: 512
  timeout: 15
  events:
    - http:
        path: /forms/{id}
        method: put
deleteForm:
  handler: com.serverless.forms.deleteform.DeleteFormHandler
  memorySize: 512
  timeout: 15
  events:
    - http:
        path: /forms/{id}
        method: delete


