name: save-records-dynamo-sf-tesis
definition:
  StartAt: getPoll
  States:
    getPoll:
      Type: Task
      Resource:
        Fn::GetAtt: [getPollByTitle, Arn]
      Parameters:
        step: getPoll step
        data.$: $.data
      Next: forLoopCondition
    forLoopCondition:
      Type: Choice
      Choices:
        - Variable: "$.data.recordsSent"
          NumericLessThanPath: "$.data.recordsToSent"
          Next: buildRandomResult
      Default: succeed
    buildRandomResult:
      Type: Task
      Resource:
        Fn::GetAtt: [getRandomResult, Arn]
      Parameters:
        step: buildRandomResult step
        data.$: $.data
      Next: sendResultToSQS
    sendResultToSQS:
      Type: Task
      Resource: "arn:aws:states:::sqs:sendMessage"
      Parameters:
        MessageBody.$: $.data.randomResult
        QueueUrl: { Ref: ResultsQueue}
      ResultPath: "$.taskresult"
      Next: incrementer
    incrementer:
      Type: Task
      Resource:
        Fn::GetAtt: [incrementerFunction, Arn]
      Parameters:
        step: incrementer step
        data.$: $.data
      Next: forLoopCondition
    succeed:
      Type: Succeed
