name: save-records-dynamo-sf-tesis
definition:
  StartAt: GetPoll
  States:
    GetPoll:
      Type: Task
      Resource:
        Fn::GetAtt: [getPollByTitle, Arn]
      ResultPath: $.data
      Next: Iterator
    Iterator:
      Type: Task
      Resource: 
        Fn::GetAtt: [iteratorFunction, Arn]
      ResultPath: $.iterator
      Next: IsCountReached
    IsCountReached:
      Type: Choice
      Choices:
        - Variable: $.iterator.shouldContinue
          BooleanEquals: true
          Next: BuildRandomResult
      Default: ShouldRestart
    BuildRandomResult:
      Type: Task
      Resource:
        Fn::GetAtt: [getRandomResult, Arn]
      ResultPath: $.data
      Next: sendResultToSQS
    sendResultToSQS:
      Type: Task
      Resource: "arn:aws:states:::sqs:sendMessage"
      Parameters:
        MessageBody.$: $.data.randomResult
        QueueUrl: { Ref: ResultsQueue}
      ResultPath: "$.taskresult"
      Next: Iterator
    ShouldRestart:
      Type: Choice
      Choices:
        - Variable: $.restart.executionCount
          NumericGreaterThan: 0
          Next: Restart
      Default: Done
    Restart:
      Type: Task
      Resource:
        Fn::GetAtt: [restartFunction, Arn]
      Next: Done
    Done:
      Type: Pass
      End: true
