service: forms-api-python

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FORMS_TABLE_NAME}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FORMS_TABLE_NAME}/index/ListFormsTitles
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FORMS_TABLE_NAME}/index/SearchFormByTitle
  environment: ${file(config/serverless/environment/env.yml)}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    slim: true
    strip: false
    useDownloadCache: false
    useStaticCache: false

package:
  individually: true
  patterns:
    - '!./**'

functions:
  - ${file(config/serverless/functions/api/forms_functions.yml)}
  - ${file(config/serverless/functions/api/results_functions.yml)}



  