createPoll:
  handler: com.serverless.polls.createpoll.CreatePollHandler
  timeout: 15
  events:
    - http: # Se indica que el evento se disparará mediante una solicitud http
        path: /polls
        method: post
getPoll:
  handler: com.serverless.polls.getpoll.GetPollHandler
  timeout: 15
  events:
    - http:
        path: /polls/{id}
        method: get
updatePoll:
  handler: com.serverless.polls.updatepoll.UpdatePollHandler
  timeout: 15
  events:
    - http:
        path: /polls/{id}
        method: put
deletePoll:
  handler: com.serverless.polls.deletepoll.DeletePollHandler
  timeout: 15
  events:
    - http:
        path: /polls/{id}
        method: delete
getPollByTitle:
  handler: com.serverless.polls.getpollbytitle.GetPollByTitleHandler
  timeout: 15
  events:
    - http:
        path: /polls/getPollByTitle
        method: get