createResult:
  handler: com.serverless.results.createresult.CreateResultHandler
  timeout: 15
  events:
    - http:
        path: /results
        method: post
getResult:
  handler: com.serverless.results.getresult.GetResultHandler
  timeout: 15
  events:
    - http:
        path: /results/{id}
        method: get
updateResult:
  handler: com.serverless.results.updateresult.UpdateResultHandler
  timeout: 15
  events:
    - http:
        path: /results/{id}
        method: put
deleteResult:
  handler: com.serverless.results.deleteresult.DeleteResultHandler
  timeout: 15
  events:
    - http:
        path: /results/{id}
        method: delete


