service: forms-api-java

provider:
  name: aws
  runtime: java11
  lambdaHashingVersion: 20201221
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FORMS_TABLE_NAME}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FORMS_TABLE_NAME}/index/ListFormsTitles
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FORMS_TABLE_NAME}/index/SearchFormByTitle
  environment: ${file(config/serverless/environment/env.yml)}

package:
  individually: true
  artifact: target/${self:service}-${self:provider.stage}.jar

functions:
  - ${file(config/serverless/functions/api/forms_functions.yml)}
  - ${file(config/serverless/functions/api/results_functions.yml)}

  