service: poll-api

frameworkVersion: '2'

custom:
  secrets: ${file(.secrets.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment: ${self:custom.secrets}
  region: us-east-1
  iamRoleStatements: # Se crea un rol con los permisos necesarios para interactuar con DynamoDB
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: # Le indicamos el recurso para el cual aplica el rol en cuestión
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.secrets.TABLE_NAME}"
    - Effect: "Allow"
      Action:
        - dynamodb:Query
      Resource: # Le indicamos el recurso para el cual aplica el rol en cuestión
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.secrets.TABLE_NAME}/index/ListPollsTitles"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.secrets.TABLE_NAME}/index/SearchPollByTitle"

functions:
  createPoll:
    handler: handler.createPoll
    events:
      - http: # Se indica que el evento se disparará mediante una solicitud http
          path: /poll
          method: post
  updatePoll:
    handler: handler.updatePoll
    events:
      - http: # Se indica que el evento se disparará mediante una solicitud http
          path: /poll/{id}
          method: put
  getPoll:
    handler: handler.getPoll
    events:
      - http: # Se indica que el evento se disparará mediante una solicitud http
          path: /poll/{id}
          method: get
  deletePoll:
    handler: handler.deletePoll
    events:
      - http: # Se indica que el evento se disparará mediante una solicitud http
          path: /poll/{id}
          method: delete
  getAllPolls:
    handler: handler.getAllPolls
    events:
      - http: # Se indica que el evento se disparará mediante una solicitud http
          path: /polls
          method: get
  getPollByTitle:
    handler: handler.getPollByTitle
    events:
      - http: # Se indica que el evento se disparará mediante una solicitud http
          path: /getPoll
          method: get